# build-system

[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

# project
[project]
authors = [{name = "Derek Wan", email = "d.wan@icloud.com"}]
dependencies = []
dynamic = ["version"]
name = "dycw-nitpick"
readme = "README.md"
requires-python = ">= 3.12"

[project.optional-dependencies]
dev = ["hatch"]

# hatch
[tool.hatch]

[tool.hatch.build]
sources = ["src"]

[tool.hatch.build.targets.wheel]
packages = ["src/dycw_nitpick"]

[tool.hatch.version]
path = "src/dycw_nitpick/__init__.py"
