#

# pre-commit
[[".pre-commit-config.yaml".repos]]
repo = "https://github.com/dycw/pre-commit-hooks"

[[".pre-commit-config.yaml".repos.hooks]]
args = ["--python-version=3.10"]
id = "run-uv-pip-compile"

# project
["pyproject.toml".project]
requires-python = ">= 3.10"

# pyright
["pyproject.toml".tool.pyright]
pythonVersion = "3.10"

# ruff
["pyproject.toml".tool.ruff]
target-version = "py310"
