#

# project
["pyproject.toml".project]
requires-python = ">= 3.10"

# black
["pyproject.toml".tool.black]
target-version = ["py310"]

# pyright
["pyproject.toml".tool.pyright]
pythonVersion = "3.10"

# ruff
["pyproject.toml".tool.ruff]
target-version = "py310"
