#

# project
["pyproject.toml".project]
requires-python = ">= 3.11"

# black
["pyproject.toml".tool.black]
target-version = ["py311"]

# pyright
["pyproject.toml".tool.pyright]
pythonVersion = "3.11"

# ruff
["pyproject.toml".tool.ruff]
target-version = "py311"
