#

# pre-commit
[[".pre-commit-config.yaml".repos]]  # dycw
repo = "https://github.com/dycw/pre-commit-hooks"

[[".pre-commit-config.yaml".repos.hooks]]
args = ["--python-version=3.11"]
id = "run-uv-pip-compile"

# project
["pyproject.toml".project]
requires-python = ">= 3.11"

# basedpyright
["pyproject.toml".tool.basedpyright]
pythonVersion = "3.11"

# ruff
["pyproject.toml".tool.ruff]
target-version = "py311"
