[[".pre-commit-config.yaml".repos]]
repo = "https://github.com/jazzband/pip-tools"

[[".pre-commit-config.yaml".repos.hooks]]
args = [
  "--allow-unsafe",
  "--generate-hashes",
  "--quiet",
  "--upgrade",
  "pyproject.toml",
]
files = '^pyproject\.toml$'
id = "pip-compile"

[[".pre-commit-config.yaml".repos.hooks]]
args = [
  "--allow-unsafe",
  "--extra=dev",
  "--generate-hashes",
  "--output-file=requirements-dev.txt",
  "--quiet",
  "--upgrade",
  "pyproject.toml",
]
files = '^pyproject\.toml$'
id = "pip-compile"
